server {
    include snippets/block-scanners.conf;
    if ($host = evolution.axiomacloud.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name evolution.axiomacloud.com;
    return 301 https://$host$request_uri;

    client_max_body_size 50M;        # ← agregás esta línea


}

server {
    include snippets/block-scanners.conf;
    listen 443 ssl;
    server_name evolution.axiomacloud.com;
    ssl_certificate /etc/letsencrypt/live/evolution.axiomacloud.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/evolution.axiomacloud.com/privkey.pem; # managed by Certbot


    location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_read_timeout 300s;
    }

}
