server {
    include snippets/block-scanners.conf;
    server_name prd.axiomacloud.com;

    location /axio-agent/ {
        proxy_pass         http://127.0.0.1:3005/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;

        # Solo acepta requests de cuthulu
        allow 170.78.73.245;
        deny  all;
    }

    location / {
        return 404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/prd.axiomacloud.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/prd.axiomacloud.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    include snippets/block-scanners.conf;
    if ($host = prd.axiomacloud.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name prd.axiomacloud.com;
    return 404; # managed by Certbot


}